defaults:
  - _self_
  - llm_template: llm_template
  - initial_advice: initial_advice

problem_type: "classification"
model_type: "random_forest_classifier"
# choice from catboost_classifier, linear_classifier, svm_classifier, random_forest_classifier
classification:
  metrics:
    - "accuracy"
    - "f1"
    - "precision"
    - "recall"
    - "roc_auc"
  datasets:
    - 40945
    - 31
    - 1464
    - 1504
    - 334
    - 50

regression:
  metrics:
    - "mean_absolute_error"
    - "mean_squared_error"
    - "root_mean_squared_error"
    - "mean_squared_logarithmic_error"
    - "median_absolute_error"
  datasets:
    - 8
    - 204
    - 210
    - 560

llm:
  llm_backend: "vsegpt"
  experiment_description: ${llm_template.experiment_description}
  output_format: ${llm_template.output_format}
  available_nodes_description: ${llm_template.available_nodes_description}
  instruction: ${llm_template.instruction}
  message_order: ${llm_template.message_order}
  operation_split: "->"
  operators:
    - "add"
    - "sub"
    - "mul"
    - "div"
    - "pca"
    - "fillnamean"
    - "fillnamedian"
    - "std"
    - "minmax"
    - "drop"
#    - "frequencyencoding"
    - "binning"
    - "labelencoding"
    - "onehotencoding"
  sleep_timeout: 20
  vsegpt:
    _target_: langchain_openai.ChatOpenAI
    temperature: 0
    model_name: "gpt-3.5-turbo"

    api_key: "sk-or-vv-..."
    openai_api_base: "https://api.vsegpt.ru/v1/"
  openai:
    _target_: langchain_openai.ChatOpenAI
    temperature: 0
    model_name: "gpt-3.5-turbo"
    organization: "org-..."  # original
    api_key: "sk-..."
  groq:
    _target_: langchain_groq.ChatGroq
    model_name: "llama3-70b-8192"
    temperature: 0
    groq_api_key: "gsk_..."

dataset_advice: ${initial_advice}

experiment:
  give_initial_advice: True # or False if no multistep optimization is needed
  test_mode: False
# choice from random_search, random_predefined, interactive or None
  num_iterations: 10
  root_path: "/home/root/path"
  save_results: True
